### ISSUE TITLE
Hover tooltips do not show in correct place when window size is changed.

### ISSUE THREAD

**Issue by huantianad** [megaminerjenny/HeavenStudio#110]
When hovering over certain menu items, a helpful tooltip pops up with the name of that item as well as sometimes keybind info. With a normal window size these popups show up properly near the mouse; however, when the window size is increased, the location of these tooltips is wildly out of place.

OS: Manjaro Linux, Kernel 5.18.5
Commit: 36c110e4adc06a616f052fee8b483f93c29c91a6

Example:
https://user-images.githubusercontent.com/20760920/175431341-86036f24-1297-42c8-912e-17050795128a.mp4

**Comment by Starpelly** [comment]
The entire UI should've been redone a long time ago. A main criticism I have is that instead of making proper layouts that respond accordingly they decided to just scale the viewport down.

I personally do not know the fix to this, but I would suggest they fix that as that would solve so many problems that may arise in the future.

**Comment by huantianad** [comment]
I do agree that the UI needs some redesigning. For example, there's a mix of keyboard inputs and mouse inputs, i.e. you use arrow keys to select events, then mouse to drag onto timeline. Ideally both an all keyboard and all mouse workflow should be supported.

**Comment by ThatZeoMan** [comment]
> 

yeah, we're working on an editor rewrite and redesign. trust me, it already causes problems lol

**Comment by minenice55** [comment]
Fixed in #124
